apiVersion: apps/v1
kind: Deployment
metadata:
  name: lammps-native
spec:
  selector:
    matchLabels:
      run: lammps
  replicas: 5
  template:
    metadata:
      name: mpi-worker
      labels:
        run: lammps
    spec:
      containers:
        - name: mpi-worker
          image: faasm/experiment-lammps-native:0.0.1
          imagePullPolicy: Always
          #imagePullPolicy: IfNotPresent
